import type { Metadata } from "next";

import "./globals.css";
import { Footer, Navbar } from "@/components";

export const metadata: Metadata = {
  title: "Flay | Website Travel",
  description: "Generated by RUI Company",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
    
    <link rel="shortcut icon" href="logo-c.svg" type="image/x-icon"/>
</head>
      <body >
        <Navbar/>
       <main className="relative overflow-hidden">
       {children}
       </main>
        <Footer/>
        </body>
    </html>
  );
}
